[build-system]
requires = ["flit_core =8.8.1"]
build-backend = "flit_core.buildapi"

[project]
name = "VersaTul"
authors = [{name = "Bjorn Williams", email = "bjorn.williams@gmail.com"}]
dynamic = ["version", "description"]
